version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes: # remove when uploading
      - ./frontend/src:/app/src
      - /app/node_modules
      - ./frontend/public:/app/public 

  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes: # remove when uploading
      - .//backend/src:/app/src
      - /app/node_modules
    depends_on:
      - mysql
      - mongodb
    environment:
      # MySQL config
      MYSQL_DB_HOST: mysql
      MYSQL_DB_PORT: 3307
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: pass
      MYSQL_DB_NAME: ise_mysql
      # MongoDB config
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017
      MONGO_DB_NAME: ise_mongo

  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ise_mysql
    volumes:
      - mysql-data:/var/lib/mysql # remove when uploading
      - ./db/create.sql:/docker-entrypoint-initdb.d/create.sql

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 27017:27017
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: pass
    volumes: # remove when uploading
      - mongo-data:/data/db

volumes:
  mysql-data:
  mongo-data: